### PR TITLE
(WIP) Experimental implementation of the RIVA 128

### PR DESCRIPTION
**Pull request by qeeg**

### CODE REVIEW

**Comment by CRTRevivalDreamer** [comment]
Here's the RIVA 128's datasheet.
It'll be of great help to you, qeeg!
[RIVA128.pdf](https://github.com/86Box/86Box/files/5843423/RIVA128.pdf)

**Comment by qeeg** [comment]
@CRTRevivalDreamer Don't you think I would've already seen the datasheet for this thing? It barely tells you anything. Datasheet? More like DataSHIT.

**Comment by explorerdotexe** [comment]
> @CRTRevivalDreamer Don't you think I would've already seen the datasheet for this thing? It barely tells you anything. Datasheet? More like DataSHIT. Don't be so patronizing next time and actually dig up something that I HAVEN'T seen before before saying "it'll be of great help to me".

fuckin owned

**Comment by CRTRevivalDreamer** [comment]
Sorry for the inconvenience, but I couldn't find the RIVA TNT or TNT2 datasheets!

**Comment by OBattler** [comment]
Closed because the author of the pull request has been blocked from the repository.

**Comment by waltje** [comment]
Again? :)

    On Thursday, September 9, 2021, 11:53:40 AM EDT, Miran Grča ***@***.***> wrote:  
 
 


Closed because the author of the pull request has been blocked from the repository.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
