### PR TITLE
Machine flag cleanups and other assorted machine changes

### LINKED ISSUE #4060: Many 486 boards allow configuration with internal IDE controller that doesn't exist
### What happened?

Almost all of the 486 machines give the option of an internal IDE controller in the emulator settings. Early boards don't have any. Some later models came with a single controller on board, with generally only the last 486 boards having dual controllers.

Looking at the socket 3 machines, the following are incorrect and have no onboard controllers in reality:

AOpen Vi15G
ASUS 486SV2G (GX4)
DTK PKM-0038S E-2
Epox 486SX/DX Green
MSI MS-4134
J-Bond PCI400C-B
Tekram G486IP

And these machines should only have a single IDE controller on board:

ASUS PVI-486AP4
Intel Classic/PCI ED
ASUS PCI/I-486SP3
ASUS PCI/I-486SP3G

I haven't looked at the earlier socket boards.

### Configuration file

```ini
N/A
```

### Operating system

N/A

### CPU

N/A

### 86Box version

5403

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Example, this ASUS board clearly has no IDE controllers. The manual tells you you have to install an IDE controller into a slot to use IDE. The emulator however allows you to invent an internal controller.

https://theretroweb.com/motherboards/s/asus-vl-i-486sv2gx4

### PR DESCRIPTION
**Pull request by cartifanwlr**
Summary
=======
Thanks to theretroweb.com, we are able to identify which features and hardware are available on the boards we emulate. This PR aims to add devices on boards that were previously not there even if they should've, and removed hardware from machines that lack those. Notes have been left for future internal hardware implementation. As some machines have been identified, they have been renamed and rearranged; turns out the Award "486" didn't support 486es at all!

Checklist
=========
* [x] Closes #4060 
* [x] I have discussed this with core contributors already
* [x] This pull request requires changes to the ROM set
  * [x] I have opened a roms pull request - https://github.com/86Box/roms/pull/240/

References
==========
[The Retro Web](https://theretroweb.com)
[ManualsLib](https://manualslib.com)

### CODE REVIEW

**Comment by mfmcosta** [comment]
[VIA VT82C495] FIC 4386-VC-HD is used in Olivetti PCS30 & Olivetti PCS40
this machine supports 386DX as well as 486SX/DX/DX2 - see manuals @ TheRetroWeb

[NEAT] Phoenix 286 clone is the "Arche AMA-2010" or "Kenitec 286 Plus" (the BIOS ROM file is... kenitec.bin)
Kenitec was Arche's european branch

**Comment by cartifanwlr** [comment]
> [VIA VT82C495] FIC 4386-VC-HD is used in Olivetti PCS30 & Olivetti PCS40 this machine supports 386DX as well as 486SX/DX/DX2 - see manuals @ TheRetroWeb
> 
> [NEAT] Phoenix 286 clone is the "Arche AMA-2010" or "Kenitec 286 Plus" (the BIOS ROM file is... kenitec.bin) Kenitec was Arche's european branch

Noted, thanks.

**Comment by cartifanwlr** [comment]
Oh it looks like we emulate the 486 only model, the 486-VC-HD and not the 4**3**86-VC-HD.

**Comment by mfmcosta** [comment]
[8088] AMI XT Clone is a MICOMS XL-7 TURBO - the same BIOS ROM is hosted @ TheRetroWeb

**Pull request merged**
