### PR TITLE
IBM 386SLC/486SLC/486 Blue Lightning emulation

### PR DESCRIPTION
**Pull request by nerd73**
This pull request adds preliminary emulation of the IBM SLC and Blue Lightning CPUs to various 286 and 386 PS/2 machines.

### CODE REVIEW

**Comment by darkstar** [comment]
the indenting looks horrible on this. Granted, some of this is because the original source already mixes tabs and spaces, but three different indentings (1 tab vs. 2 tabs vs. 8 spaces) in 3 consecutive lines? ;-)
https://github.com/86Box/86Box/pull/502/commits/719534c518c817f850391d355d84f1ce4473f9b4#diff-ab781aca9f2f3f40226effc08a525b77R263

**Comment by nerd73** [comment]
Thanks, I've done some indenting fixes. The indenting seemed alright in Notepad++, but I guess GitHub uses different standards for indent lengths.

**Comment by tiseno100** [comment]
Lenghts in the 86Box code are a mess in general. A mixture of spaces and tabs. So it's fine at least for me.

**Comment by dhrdlicka** [comment]
The indenting in 86Box is 4 spaces for first level, 1 tab for second level, 2 tabs for third level and so on.

It might not hurt to agree on using something more consistent though.

**Comment by OBattler** [comment]
> It might not hurt to agree on using something more consistent though.
I absolutely agree.

**Pull request merged**
