### PR TITLE
Update and rename src/win/languages/ru-RU.rc to src/победить/языки/ru…

### PR DESCRIPTION
**Pull request by maximus105**
Summary
=======
Correction of some grammatical errors in Russian translation.

Checklist
=========
* [ ] Closes #xxx
* [ ] I have discussed this with core contributors already
* [ ] This pull request requires changes to the ROM set
  * [ ] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/

References
==========
_Provide links to datasheets or other documentation that helped you implement this pull request._

### CODE REVIEW

**Comment by OBattler** [comment]
Why did you rename the directory (to wrong Russian, at that - "win" here stands for Windows, yet you seem to have translated it literally)?

**Comment by OBattler** [comment]
Committed (without the path change).

**Comment by maximus105** [comment]
> Почему вы переименовали каталог (на неправильный русский язык, при этом «победа» здесь означает Windows, а вы, кажется, перевели это буквально)?



> Why did you rename the directory (to wrong Russian, at that - "win" here stands for Windows, yet you seem to have translated it literally)?

Perhaps I pressed something wrong. I only corrected the wrong letters in the words (which I posted about earlier).

**Comment by maximus105** [comment]
My corrections in the Russian translation have not been added? I checked in build 3338. Or have they not been added to the latest 86Box build yet?

**Comment by OBattler** [comment]
They were added, check the .rc file.

**Comment by maximus105** [comment]
It looks like they haven't been added. Nothing has changed in the .rc file.

https://github.com/86Box/86Box/blob/master/src/win/languages/ru-RU.rc
Or am I looking in the wrong place?

**Comment by maximus105** [comment]
This link added fixes:
https://github.com/86Box/86Box/blob/feature/machine_and_kb/src/win/languages/ru-RU.rc
And there are no fixes at this link:
https://github.com/86Box/86Box/blob/master/src/win/languages/ru-RU.rc
Build 3340 does not include these fixes either.

**Pull request closed without merging**
