### PR TITLE
Qt: MAC address configuration

### PR DESCRIPTION
**Pull request by Cacodemon345**
Summary
=======
Qt: MAC address configuration

Checklist
=========
* [ ] I have discussed this with core contributors already
* [ ] This pull request requires changes to the ROM set
  * [ ] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/

References
==========
None.

### CODE REVIEW

**Comment by OBattler** [comment]
I'll have to manually port these changes since I have major device configuration changes on my end as I'm trying to add the possibility of BIOS-dependent configuration options (which are going to be needed for eg. graphics cards where different BIOS'es can mean eg. different minimum and maximum RAM amounts).

**Comment by lemondrops** [comment]
Also, how does this behave when there's no MAC address generated yet (i.e. when a network card is newly added?)

**Comment by Cacodemon345** [comment]
If the user doesn't open the configuration settings for the network device after selecting it, the MAC address is automatically generated. If the user does after selecting it (but before saving the settings), and he/she doesn't alter the default address of 00:00:00 in it and leaves it as is when confirming the settings, it will be saved as 00:00:00 and it will not be randomly generated when the emulated machine starts with this network device.

**Comment by dhrdlicka** [comment]
This is likely out of scope but we might want to consider letting the user change the entire MAC address and not only the second half. Especially if we want to expose this as a UI option

**Comment by OBattler** [comment]
> This might be out of scope but we should consider letting the user change the entire MAC address and not only the second half. Especially if we want to expose this as a UI option

Given that this can affect device detection (see NE2000), I don't tink that's a good idea.

**Comment by dhrdlicka** [comment]
That raises the question whether there is any point in exposing this in the user interface in the first place if the full MAC address cannot be changed. I cannot think of a scenario where a user would only want to change the second half of the MAC address. That is, other than a MAC address conflict, which would be so rare that it makes more sense to just instruct users to remove the conflicting address from the config to generate a new one.

Most (if not all) usecases for letting the MAC address be configurable expect it to be configurable in its full length. Usually that would involve using PCap on some strange network setup where the router keeps track of client MAC addresses.

And sure enough, when an option to change the MAC address is exposed, it lets you change the full address:
image
image

**Comment by lemondrops** [comment]
> Given that this can affect device detection (see NE2000), I don't tink that's a good idea.

Well, if a user overrides the vendor portion to something that affects device detection, it would be on them and not us, wouldn't it?

> And think of it this way - real cards of the same vendor would have the same first half of the MAC address and only differ in the second half.

Good thing 86Box is an emulator and not real hardware :D Also to be pedantic, the "same first half" part is only true if the vendor has only one OID, and many vendors have multiple.

**Comment by dhrdlicka** [comment]
> Speaking of VMware, it automatically detects if a VM was moved from its previous location, and asks the user if they moved or copied it, so that it can generate a new MAC address if the latter option is selected, avoiding a conflict in the example case above. Maybe something like tht could be implemented in 86Box?

@lemondrops We could generate the second half of the MAC address as a hash of the VM path and check if they match on startup. If not, then ask the user whether the address should be regenerated. If they don't want to regenerate it, then save a boolean flag to the config to disable the check.

**Pull request closed without merging**
