### PR TITLE
Philips and Olivetti bugfixes (revised)

### PR DESCRIPTION
**Pull request by EngiNerd89**
Summary
=======
Fixed Philips P3120 FDC bug: internal FDC controller now works
Fixed Olivetti M300 NVRAM bug: when initialized for the first time, NVRAM prevented internal FDC and HDC controllers from working once CMOS settings were saved. A specific NVRAM device for Olivetti machines has been created in nvr_at.c

Checklist
=========
* [X] Closes https://github.com/86Box/86Box/issues/1160
* [X] I have discussed this with core contributors already
* [ ] This pull request requires changes to the ROM set
* [ ] I have opened a roms pull request

References
==========
N/A

### CODE REVIEW

**Comment by OBattler** [comment]
The Olivetti M300's have the same PIT problem as the 486 (though I need to try with the reverted ROM read timing, maybe that will fix it?), as such they are likely to be removed (but might be kept if someone figures out a way to fix that stuff).

**Comment by OBattler** [comment]
OK, that did not fix them, so the Olivetti M300's and 486 are getting removed.

**Comment by EngiNerd89** [comment]
That's weird, as M300 machines work fine on my end. Maybe these PIT issues are host CPU sensitive? FYI my host machine is a ThinkPad X230 with an i5-3320m

**Comment by OBattler** [comment]
They appear to work fine, but if you notice, they restart themselves a few times on POST, that's because of the PIT problems. The M300's just don't explicitly say what's wrong, unlike the 486.

**Comment by EngiNerd89** [comment]
You're right. When those machines are cold-started, the 86box window resizes 2 times before the POST messages (Resident Diagnostics) is shown. I hadn't payed much attention to this, as I was thinking it was the normal behavior of the VGA adapter, and not a PIT issue. While testing, I also found out the cause of non-working on-board graphics adapters some users were lamenting: when machine names were renamed and directory paths were changed, the path of the on-board VGA BIOS was not changed.

That said, what should we do now? Should I close this commit and create a new one only with fixes for Philips machines, leaving the Olivetti ones in my local repository? Or should this commit get approved first and later, once the decision is finalized, the M300 machines get removed?

**Comment by OBattler** [comment]
> That said, what should we do now? Should I close this commit and create a new one only with fixes for Philips machines, leaving the Olivetti ones in my local repository? Or should this commit get approved first and later, once the decision is finalized, the M300 machines get removed?

You should do the former (but don't actually remove the machines yet as they are removed on my end and you making a removal PR would cause a conflict with my local changes) as the decision is finalized and the machines have already been removed on my end.

**Pull request closed without merging**
