### PR TITLE
Update gettingstarted in README.md

### PR DESCRIPTION
**Pull request by yoosofan**

### CODE REVIEW

**Comment by daviunic** [comment]
May I ask what is the point of this change?

**Comment by yoosofan** [comment]
Correcting just a link. You can do it yourself. It is just a reminder to fix it. I just check the readme and find this dangling link.

**Comment by daviunic** [comment]
Ah yes, the link is indeed broken, but all it needs is https:// in front, so it redirects to the actual page on the site, instead of a file on the website repo.

**Comment by yoosofan** [comment]
Okay

**Comment by daviunic** [comment]
Issue fixed, thanks for the heads up.

**Comment by yoosofan** [comment]
u r welcome

**Pull request closed without merging**
