### PR TITLE
Packard Bell PB430 emulation

### PR DESCRIPTION
**Pull request by anabate123**

### CODE REVIEW

**Comment by tiseno100** [comment]
The PB430 can allocate up to 64MB of RAM & also please provide a PR on roms containing the PB430 ROM

**Comment by anabate123** [comment]
Here's the pull request right here.
https://github.com/86Box/roms/pull/8

**Comment by tiseno100** [comment]
Your machine seems to fail with "Password Violation". You need to add the register responsible of handling it

**Comment by anabate123** [comment]
It failed

**Pull request closed without merging**
