### PR TITLE
qt: Fix editing fields at Hard Disks section

### PR DESCRIPTION
**Pull request by Cacodemon345**
Summary
=======
qt: Fix editing fields at Hard Disks section

Fields that can be changed by combo box selections are made not directly editable. CHS and Size values are made editable properly.

Checklist
=========
* [ ] I have discussed this with core contributors already
* [ ] This pull request requires changes to the ROM set
  * [ ] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/

References
==========
None.

### CODE REVIEW

**Comment by lemondrops** [comment]
As I said in https://github.com/86Box/86Box/pull/3084#issuecomment-1418127309, the tables in other pages (floppy and CD-ROM, other removables) also have all their fields editable. Unlike the hard disks one, all the fields can be changed by combo boxes, though.

**Comment by cold-brewed** [comment]
I have a few concerns with making the hdd field editable, at least in its current state.

First, the interface wasn't really designed with this in mind and would need some updates. See screenshot:
 
hdd edit

Due to the column size it's difficult / impossible to see the values being edited. The interface would need some updating and testing across platforms to avoid issues like above.

Second: Changing the CHS or size is a potentially *destructive* action on an existing drive from the perspective of the guest. As this is written, it just accepts any CHS / size modifications without any warnings. I feel like if you're going to enable this functionality there should at least be some warnings or guardrails involved. 

By the time someone updates the CHS / size with no warnings and restarts the guest it may be too late.

**Comment by dhrdlicka** [comment]
> Changing the CHS or size is a potentially _destructive_ action on an existing drive from the perspective of the guest. As this is written, it just accepts any CHS / size modifications without any warnings. I feel like if you're going to enable this functionality there should at least be some warnings or guardrails involved.
> 
> By the time someone updates the CHS / size with no warnings and restarts the guest it may be too late.

Personally I think this shouldn't even be exposed from the UI at all. If a user needs to change the CHS of an existing drive, they can always edit the configuration file manually.

**Comment by Dizzy611** [comment]
Hard pass on this idea. There is almost no reason for a user to want to edit the CHS on an existing drive and if they think they need to then we've got an X-Y problem going on. 

Suggest this does *NOT* get merged.

**Comment by Cacodemon345** [comment]
I would be considering just exposing size editing (which makes more sense) but a proper 1:1 roundtrip CHS<->MiB conversion is impossible with our current code.

**Pull request closed without merging**
