### PR TITLE
Feature/external fdc

### PR DESCRIPTION
**Pull request by TC1995**

### CODE REVIEW

**Comment by waltje** [comment]
This is not an "external" FDC. It is a bus-based one, which 99% of all FDC's were prior to SIOs in 486+ chipsets.


     On Tuesday, June 16, 2020, 06:35:04 PM EDT, TC1995 <notifications@github.com> wrote:  
 
 
You can view, comment on, or merge this pull request online at:

  https://github.com/86Box/86Box/pull/818

Commit Summary
   
   - Added external Floppy disk controller support.
   - Fixed the UI for the external FDC.
   - Fixed the fix.
   - Fixed the fix 2.
   - Fixed the fix 3 (grr).
   - Fixed the fix 4.
   - Added fdc_ext.h header to pc.c
   - (Re-)added the Deskpro 386, but only in the development/incomplete section of the code definitions.

File Changes
   
   -  M src/config.c (21) 
   -  M src/cpu/cpu.h (1) 
   -  M src/cpu/cpu_table.c (10) 
   -  M src/floppy/fdc.c (116) 
   -  A src/floppy/fdc_pii15xb.c (208) 
   -  M src/include/86box/config.h (3) 
   -  M src/include/86box/fdc.h (4) 
   -  A src/include/86box/fdc_ext.h (43) 
   -  M src/include/86box/machine.h (3) 
   -  M src/include/86box/resource.h (3) 
   -  M src/include/86box/scsi_x54x.h (4) 
   -  M src/machine/m_at.c (4) 
   -  M src/machine/m_at_compaq.c (32) 
   -  M src/machine/m_tandy.c (5) 
   -  M src/machine/m_xt.c (5) 
   -  M src/machine/m_xt_compaq.c (4) 
   -  M src/machine/m_xt_zenith.c (7) 
   -  M src/machine/machine_table.c (3) 
   -  M src/pc.c (3) 
   -  M src/scsi/scsi_aha154x.c (136) 
   -  M src/scsi/scsi_buslogic.c (2) 
   -  M src/scsi/scsi_x54x.c (2) 
   -  M src/win/86Box.rc (7) 
   -  M src/win/Makefile.mingw (3) 
   -  M src/win/win_settings.c (94) 

Patch Links:
   
   - https://github.com/86Box/86Box/pull/818.patch
   - https://github.com/86Box/86Box/pull/818.diff

**Comment by dhrdlicka** [comment]
Why does this PR include Deskpro 386 stuff?

**Comment by TC1995** [comment]
I tried to implement the 287/XL fpu on it, but it still halts there.

**Comment by TC1995** [comment]
Anyway, the latest part of this pr removes the deskpro 386 from the machine table.

**Pull request merged**
