### PR TITLE
Downsampling to 44.1 kHz while SB aliasing on 44.1 kHz output hosts exists

### PR DESCRIPTION
**Pull request by PythonBlue**
Downsampling to 44.1 kHz while SB aliasing on 44.1 kHz output hosts exists

Summary
=======
As mentioned on the Discord, I noticed aliasing issues with SoundBlaster sound cards on my 44.1 kHz audio output on my host, possibly other cards as well (though not the ES1371). Turned out it's partially because the entire project assumes the higher output sample rate of 48 kHz. Since I doubt I'm the only one still focused on the CD quality sample rate of 44.1 kHz, I'm making this pull request as a hopefully-temporary workaround for the SB cards on hosts with 44.1 kHz audio output, especially since I doubt I'm the only audiophile who might be interested in retro tech emulation like this.

Checklist
=========
* [ ] Closes #xxx
* [x] I have discussed this with core contributors already
* [ ] This pull request requires changes to the ROM set
* [ ] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/

References
==========
_Provide links to datasheets or other documentation that helped you implement this pull request._

### CODE REVIEW

**Comment by PythonBlue** [comment]
NVM...closing the pull request because I don't appreciate being bullied in the server over something as trivial as this...all I'm going to say to the person of concern: I never did say it was a fix, nor did I ever say higher sample rates aren't a thing.

**Comment by jriwanek** [comment]
Note to self: 44100, 48000, 49716 and 96000 for initial sample rates.

**Comment by PythonBlue** [comment]
Take it back: it took their making me doubt myself to force-change my output samplerate for their preference to 48 kHz, and I failed to notice the aliasing that way, so I'm happy to say they were wrong.

**Comment by OBattler** [comment]
This is going to need some rethinking now that we allow emulating up to 4 sound cards at the same time.

**Comment by OBattler** [comment]
I'm closing this even though kagamiin confirmed the aliasing, because I'm going to try to figure out a proper solution for this in 4.3.

**Pull request closed without merging**
