### PR TITLE
Draft: Debian build system

### PR DESCRIPTION
**Pull request by mariuszkurek**
Summary
=======
This PR adds the files required to build *.deb packages and `.gitignore` rules associated with them. Tested on Ubuntu 22.04 amd64 and Debian 11 arm64, the latter requires `cmake` from backports, because `CMakePresets.json` requires 3.21. If we skip `ninja` and, as a result, this file, it should be possible to build it on Debian 10 and Ubuntu 20.04 by editing `debian/rules`.

It's a draft because:
- I haven't filled `debian/copyright`
- I don't know how `debian/watch` works, but I think it's irrelevant if it isn't in some kind of a Debian repository.
- It'd be nice to add building packages in GitHub Actions.
- Building is done by using `dpkg-buildpackage -us -uc`. The arguments skip signing, which could be potentially avoided.

Checklist
=========
* [ ] Closes #xxx
* [X] I have discussed this with core contributors already
* [ ] This pull request requires changes to the ROM set
  * [ ] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/

References
==========
I followed this tutorial: https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.en.pdf

### CODE REVIEW

**Comment by summer-dev** [comment]
@mariuszkurek 
Hi，I tried to package your forked repo with sbuild which is debian official packaging method.

However,it failed  complaining depedency issue

here is the full building log:

https://pastebin.com/x5ZjXERT

I'm asking help from debian community, and it could be faster if you can give me some clues.

thanks

**Comment by mariuszkurek** [comment]
@summer-dev 
```
Host Architecture: riscv64
Build Architecture: riscv64
```
Here's your problem. I whitelisted only i386, amd64, armhf and arm64 because only these platforms have dynarec. You can change debian/control L22 to Architecture: all (I think) or add riscv64 to this line, but it will be noticeably slower than the others.

**Comment by summer-dev** [comment]
Thanks  for your kind suggestion.

Accorging to my knowledge,debian official recommends developers to package .deb with sbuild. So far,it is so good you can make it build through dpkg-buildpackage. 😊

I modified debian/* files according to your guide.

I tried to sbuild within both amd64 and riscv64 chroot environment.

Neither of the sbuild succeeded,it ‘s all about the qt-* related dependency.

***@***.***

Finally,I am a little curious why you tried to merge these debian files into github,these work maybe more appropriate done by debian community.Besides,someone had planned to porting 86Box to debian,but with no further progress. Ref:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=996637


I wish I can continue this porting job if possible.:)

----------------------------------------------------------------
Live for truth,goodness and beauty
----------------------------------------------------------------


________________________________
发件人: Mariusz Kurek ***@***.***>
发送时间: Monday, October 24, 2022 6:58:16 PM
收件人: 86Box/86Box ***@***.***>
抄送: summer-dev ***@***.***>; Mention ***@***.***>
主题: Re: [86Box/86Box] Draft: Debian build system (PR #2726)


@summer-dev<https://github.com/summer-dev>

Host Architecture: riscv64
Build Architecture: riscv64


Here's your problem. I whitelisted only i386, amd64, armhf and arm64 because only these platforms have dynarec. You can change debian/control L22 to Architecture: all (I think) or add riscv64 to this line, but it will be noticeably slower than the others.

**Comment by mariuszkurek** [comment]
I'm merging it here because potentially you can make GitHub Action to create a deb package every commit.
Truth be told, I haven't checked on debian.org if anyone tried to add it, but I can see it's from back when it only had SDL with no interface, so that might be why it didn't pick up.
I'm not sure how adding packages to Debian work, but if someone wants to do that, I don't see a reason why not. The only problem is that as of now there's no ready subset of ROM files that are free, so I don't know if it counts as main or contrib.
At least the following files from ROMs repo are on free licenses: machines/{xi8088, openxt}, icons, hdd/xtide
The rest isn't even suitable for non-free I believe.

**Comment by summer-dev** [comment]
@mariuszkurek Hi, an extra dependency is needed :libqt5opengl5-dev, after adding this to debian/control, `Build-Depends ` field  the sbuild succeed.
I think this dep is necessay,although I'm not familiar with github actions.

There are two  warnings at the final stage:
```
E: 86box: extended-description-is-empty
E: 86box: no-copyright-file
```
The above warnings are harmless.

**Comment by mariuszkurek** [comment]
I'm aware of both of these warnings (although E sounds more like error :P), although I forgot to mention the latter in my initial message. I'll add this dependency right now.

**Comment by summer-dev** [comment]
@mariuszkurek 
Sorry for the inconvenience,could you please fill in more infos about `years` and `author` to debian/copyright ? see below
```

Files: *
Copyright: <years> <put author's name and email here>
           <years> <likewise for another author>
License: GPL-2.0+
```

**Pull request merged**
